#!/bin/zsh

alias ls="LC_ALL=C.UTF-8 ls -hN --color=auto --group-directories-first"
alias v="$EDITOR"
alias tmux="tmux -f $XDG_CONFIG_HOME/tmux/tmux.conf"
alias yarn="yarn --use-yarnrc $XDG_CONFIG_HOME/yarn/yarnrc"
